# Generated by Django 4.2.4 on 2023-09-02 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallary',
            name='Image',
            field=models.ImageField(upload_to='productimages'),
        ),
    ]
