# Generated by Django 4.2.4 on 2023-09-02 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_gallary_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallary',
            name='Category',
            field=models.IntegerField(choices=[(1, 'SmartWatch'), (2, 'NormalWatch')], null=True),
        ),
    ]
