# Generated by Django 4.2.4 on 2023-09-03 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_gallary_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallary',
            name='Category',
            field=models.IntegerField(choices=[(1, 'SmartWatch'), (2, 'DailWatch')], null=True),
        ),
    ]
