# Generated by Django 4.2.4 on 2023-09-03 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_gallary_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallary',
            name='Category',
            field=models.IntegerField(choices=[(1, 'smartwatch'), (2, 'dailwatch')], null=True),
        ),
        migrations.AlterField(
            model_name='gallary',
            name='Gender',
            field=models.IntegerField(choices=[(1, 'male'), (2, 'female'), (3, 'unisex')], null=True),
        ),
    ]
