# Generated by Django 4.2.4 on 2023-09-03 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_rename_userlogin_userfrom'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfrom',
            name='Email',
            field=models.EmailField(max_length=40, null=True),
        ),
    ]
