# Generated by Django 4.2.4 on 2023-09-03 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_userfrom_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfrom',
            name='Name',
            field=models.CharField(max_length=50),
        ),
    ]
