# Generated by Django 4.2.4 on 2023-09-05 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_transactions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactions',
            name='cat',
        ),
    ]
